=== 8cH9azbsFifZ/hangboard/exercises/json-exercises/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "properties": {
        "exercise_name": { "type": "string" },
        "exercise_description": { "type": "string" },
        "reps": { "type": "integer" },
        "reps_range": { "type": "string" },
        "sets": { "type": "integer" },
        "sets_range": { "type": "string" },
        "time_exercise": { "type": "integer" },
        "time_pause": { "type": "integer" },
        "time_pause_set": { "type": "integer" },
        "type": { "type": "string" },
        "level_text": { "type": "string" },
        "reference": { "type": "string" }

    },
    "required": ["exercise_name"]
}

=== 8cH9azbsFifZ/hangboard/exercises/json-exercises/exercises.json
{
    "$schema": "./schema.json",
    "exercise_name": "Band Finger Extension",
    "reps_range": "12-25",
    "sets_range": "1-2", 
    "type": "Wrist & Forearm Stabillizers",
    "level_text": "Entry-level exercises shown in GREEN -- appropriate for all climbers.",
    "reference": "Eric HÃ¶rsts Training for Climbing Program"
}
